print("    *\n   * *\n  *   *\n *     *\n***   ***")
print("  *   *\n  *   *\n  *****")

print("        * ")
print("       * * ")
print("      *   * ")
print("     *     * ")
print("    *       * ")
print("   *         * ")
print("  *           * ")
print(" *             * ")
print("******     ****** ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     *     * ")
print("     ******* ")

print("        #         "*4)
print("       * *        "*4)
print("      #    #      "*4)
print("     *     *      "*4)
print("    *       *     "*4)
print("   #         #    "*4)
print("  *           *   "*4)
print(" *             *  "*4)
print(" ------     ----- "*4)
print("     *     *      "*4)
print("     *     *      "*4)
print("     *     *      "*4)
print("     *     *      "*4)
print("     *     *      "*4)
print("     *     *      "*4)
print("     -------      "*4)
